let contador = 0;
contador ++;
contador ++;
contador ++;
contador ++;
contador ++;
contador ++;
contador ++;
contador ++;
contador --;
contador += 10;
contador -= 10;
contador *=2;
contador/= 2;
console.log(contador);